<a href="https://colab.research.google.com/github/Nithya07shree/colab-notes-aiml/blob/main/torch_note.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create tensors

In [1]:
import torch

In [2]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.randn(2,3)
tensor3 = torch.randn_like(tensor1, dtype=torch.float)

In [3]:
print(f"tensor1: {tensor1}")
print(f"tensor2: {tensor2}")
print(f"tensor3:  {tensor3}")

tensor1: tensor([1, 2, 3])
tensor2: tensor([[ 0.6386, -0.3468, -0.0534],
        [-1.2349,  0.2403,  1.4320]])
tensor3:  tensor([ 0.1403, -0.6701, -1.2862])


parameters of tensors

In [5]:
print(f"shape: {tensor3.shape}")
print(f"dtype: {tensor3.dtype}")
print(f"device: {tensor3.device}")

shape: torch.Size([3])
dtype: torch.float32
device: cpu


Autograd- building the graph

In [6]:
# requires_grad = True
a=torch.tensor(2.0, requires_grad=True)
b=torch.tensor(1.0, requires_grad=True)
x=torch.tensor(3.0, requires_grad=True)

y=a+b
z=x*y

In [7]:
#how do u know the graph exists
# .grad_fn
print(y.grad_fn)
print(z.grad_fn)
print(a.grad_fn)

None


operations - verbs of pytorch

In [10]:
# * vs @
t1 = torch.tensor([[1.0,2.0],[3.0,4.0]])
t2 = torch.tensor([[5.0,6.0],[7.0,8.0]])

print(t1*t2) # element wise multiplication
print(t1@t2) # matrix multiplication

tensor([[ 5., 12.],
        [21., 32.]])
tensor([[19., 22.],
        [43., 50.]])


In [12]:
# reduction
# sum, mean, max
# in 2d tensors, dim = 0 operates vertically(cols), dim = 1 operates horizontally(rows)
# t1.mean(dim=0)
print(f"mean: {t1.mean()}")
print(f"sum: {t1.sum()}")
print(f"max: {t1.max()}")

mean: 2.5
sum: 10.0
max: 4.0


Selecting your data

In [17]:
#  basic indexing
x = torch.arange(12).reshape(3,4)
print(x)
print(x[:,2]) # get third column
print(x[1,3]) # get 1st row 3rd column

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 2,  6, 10])
tensor(7)


In [18]:
# argmax - find index of highest value
a = torch.tensor([[1,2,4,2,1],[12,3,43,2,5]])
print(a.argmax(dim=0))
print(a.argmax(dim=1))

tensor([1, 1, 1, 0, 1])
tensor([2, 2])


In [19]:
# torch.gather()
data = torch.tensor([
    [1,2,3,4],
    [2,3,4,5],
    [3,4,5,6]
])
selection = torch.tensor([[0],[1],[2]])
print(torch.gather(data,dim=1,index=selection))

tensor([[1],
        [3],
        [5]])
